name: ai_notes_uikit
description: "Помощь в подготовке к PROF26"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  storybook_flutter: ^0.14.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^7.0.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
